import { fetch } from 'ofetch'
import {
  api,
  clearDatabase,
  destroyDatabase,
  getDatabase,
  restoreDatabase,
  rebuildDatabase,
} from '#test/helpers'
import { version as uuidVersion } from 'uuid'
import { NativeHasherAdapter } from '#server/infra/adapters/nativeHasherAdapter'
import { KnexUserRepository } from '#server/infra/repositories/knexUserRepository'

describe('POST /v1/users', async () => {
  beforeEach(async () => {
    await rebuildDatabase()
  })

  afterAll(async () => {
    await destroyDatabase()
  })

  describe('Anonymous user', () => {
    const userPayload = {
      username: 'JohnDoe',
      email: 'john.doe@example.com',
      password: 'Password123!',
    }

    async function requestUserCreation(payload: Record<string, unknown>) {
      return fetch(api('/v1/users'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      })
    }

    async function requestUserCreationWithRawBody(body: string) {
      return fetch(api('/v1/users'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body,
      })
    }

    it('With unique and valid data', async () => {
      const response = await requestUserCreation(userPayload)

      expect(response.status).toBe(201)

      const userData = await response.json()

      expect(userData).toEqual({
        id: userData.id, // Assuming the ID is generated by the server
        username: userPayload.username,
        email: userPayload.email.toLowerCase(),
        created_at: userData.created_at,
        updated_at: userData.updated_at,
      })

      expect(uuidVersion(userData.id)).toBe(4)
      expect(userData).not.toHaveProperty('password')
      expect(Date.parse(userData.created_at)).not.toBeNaN()
      expect(Date.parse(userData.updated_at)).not.toBeNaN()

      const repository = new KnexUserRepository(await getDatabase())
      const hasher = new NativeHasherAdapter()
      const user = await repository.findByUsername(userPayload.username)
      const correctCompareResult = await hasher.compare(userPayload.password, user.password)
      const incorrectCompareResult = await hasher.compare('wrongpassword', user.password)

      expect(correctCompareResult).toBe(true)
      expect(incorrectCompareResult).toBe(false)
    })

    it('With duplicate data', async () => {
      const response = await requestUserCreation(userPayload)

      expect(response.status).toBe(201)

      const duplicatedUsername = { ...userPayload, email: 'jane.doe@example.com' }
      const responseDuplicateUsername = await requestUserCreation(duplicatedUsername)
      const duplicateUsernameError = await responseDuplicateUsername.json()

      expect(responseDuplicateUsername.status).toBe(409)
      expect(duplicateUsernameError.data.code).toEqual('USERNAME_ALREADY_IN_USE')
      expect(duplicateUsernameError.message).toEqual(
        'This username is already being used by someone else',
      )

      const duplicatedEmail = { ...userPayload, username: 'JaneDoe' }
      const responseDuplicateEmail = await requestUserCreation(duplicatedEmail)
      const duplicateEmailError = await responseDuplicateEmail.json()

      expect(responseDuplicateEmail.status).toBe(409)
      expect(duplicateEmailError.data.code).toEqual('EMAIL_ALREADY_IN_USE')
      expect(duplicateEmailError.message).toEqual(
        'This email is already being used by someone else',
      )

      const duplicatedUsernameCase = {
        ...userPayload,
        username: 'JOHNDOE',
        email: 'john.doe2@example.com',
      }
      const responseDuplicateUsernameCase = await requestUserCreation(duplicatedUsernameCase)
      const duplicateUsernameCaseError = await responseDuplicateUsernameCase.json()

      expect(responseDuplicateUsernameCase.status).toBe(409)
      expect(duplicateUsernameCaseError.data.code).toEqual('USERNAME_ALREADY_IN_USE')

      const duplicatedEmailCase = {
        ...userPayload,
        username: 'JohnDoe2',
        email: 'JOHN.DOE@EXAMPLE.COM',
      }
      const responseDuplicateEmailCase = await requestUserCreation(duplicatedEmailCase)
      const duplicateEmailCaseError = await responseDuplicateEmailCase.json()

      expect(responseDuplicateEmailCase.status).toBe(409)
      expect(duplicateEmailCaseError.data.code).toEqual('EMAIL_ALREADY_IN_USE')
    })

    it('With invalid data', async () => {
      const [
        invalidJsonResponse,
        missingFieldResponse,
        invalidEmailResponse,
        emptyUsernameResponse,
        whitespaceUsernameResponse,
      ] = await Promise.all([
        requestUserCreationWithRawBody('{"username": "JohnDoe"'),
        requestUserCreation({ username: 'JohnDoe', email: 'john.doe@example.com' }),
        requestUserCreation({ ...userPayload, email: 'invalid-email' }),
        requestUserCreation({ ...userPayload, username: '' }),
        requestUserCreation({ ...userPayload, username: '   ' }),
      ])

      expect(invalidJsonResponse.status).toBe(400)
      expect(missingFieldResponse.status).toBe(400)
      expect(invalidEmailResponse.status).toBe(400)
      expect(emptyUsernameResponse.status).toBe(400)
      expect(whitespaceUsernameResponse.status).toBe(422)
    })

    describe('With unexpected server errors', async () => {
      it('Database is unavailable', async () => {
        await clearDatabase()
        await destroyDatabase()

        const response = await requestUserCreation(userPayload)
        const errorResponse = await response.json()

        expect(response.status).toBe(503)
        expect(errorResponse).toEqual({
          status_code: 503,
          message: 'The operation could not be completed at this time. Please try again later.',
          data: { code: 'INTERNAL_SERVER_ERROR' },
        })

        await restoreDatabase()
      })
    })
  })
})
